import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import SeiyuuCard from "~/components/SeiyuuCard";

interface seiyuuProps {
  seiyuu: {
    mal_id: number;
    name: string;
    website_url: string;
    url: string;
    images: {
      jpg: {
        image_url: string;
      };
    };
  }[];
}

const Home: NextPage<seiyuuProps> = ({ seiyuu }) => {
  console.log(seiyuu);
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <h2>Brrrrrah</h2>
        <div>
          {seiyuu.map((seiyuu) => (
            <div key={seiyuu.mal_id}>
              <SeiyuuCard
                name={seiyuu.name}
                website_url={seiyuu.website_url}
                url={seiyuu.url}
                image_url={seiyuu.images.jpg.image_url}
              />
            </div>
          ))}
        </div>
      </main>
    </>
  );
};

export async function getServerSideProps() {
  const res = await fetch(
    "https://api.jikan.moe/v4/people?order_by=favorites&sort=desc&limit=15"
  );
  const data = await res.json();
  const seiyuu = data.data;

  return { props: { seiyuu } };
}

export default Home;
