import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

interface seiyuuProps {
  seiyuu: {
    name: string
  }[]
}

const Home: NextPage<seiyuuProps> = ({data}) => {
  console.log(data);
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <h2>Brrrrrah</h2>
      </main>
    </>
  );
};

export async function getServerSideProps() {
  const res = await fetch(
    "https://api.jikan.moe/v4/people?order_by=favorites&sort=desc&limit=15"
  );
  const data = await res.json();

  return { props: data };
}

export default Home;
